package com.netplus.coremechanism.backendRemote.model.merchants

data class Merchant(
    val account_name: Any?,
    val account_number: String?,
    val address: String?,
    val bank_code: Any?,
    val bank_type: Any?,
    val business_occupation_code: Any?,
    val contact_name: String?,
    val contact_title: String?,
    val createdAt: String?,
    val email: String?,
    val email_alert: Any?,
    val id: Int?,
    val lga_lcda: Any?,
    val mastercard_acquired_number: Any?,
    val merchant_category_code: Any?,
    val mobile_phone: String?,
    val partner_id: String?,
    val postal_code: Any?,
    val ptsp: Any?,
    val slip_footer: Any?,
    val slip_header: String?,
    val state_code: Any?,
    val terminal_model_code: Any?,
    val terminal_owner_code: Any?,
    val updatedAt: String?,
    val url: Any?,
    val verve_acquired_number: Any?,
    val visa_acquired_number: Any?
)